[tool.poetry]
name = "zpacloud-ansible"
version = "1.0.0"
description = "Ansible collection for Zscaler Private Access (ZPA)"
authors = ["Zscaler Technology Alliances <zscaler-partner-labs@z-bd.com>"]
license = "MIT"
keywords = ["zpacloud", "zpacloud-ansible", "zpa"]
readme = "README.md"
homepage = "https://github.com/zscaler/zpacloud-ansible"
repository = "https://github.com/zscaler/zpacloud-ansible"

[tool.poetry.dependencies]
python = "^3.9"
# zscaler-sdk-python = "^1.0.0"
xmltodict = "^0.12.0"
aiohttp = "^3.9.2"
dpath = "^2.1.5"
#rstcheck-core = "1.2.0"  # Using a specific version to ensure compatibility
#pydantic = "^2.0"  # Updated to meet rstcheck-core requirements

[tool.poetry.dev-dependencies]
black = "24.3.0"
pytest = "*"
coverage = "4.5.4"
pylint = "2.13.*"
pytest-xdist = "*"
pytest-mock = "*"
voluptuous = "*"
yamllint = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
#ansible-doc-extractor = "*"
rstcheck = "*"
six = "*"
pycodestyle = "*"
#ansible-core = "~2"
# from requirements.txt
certifi = "^2023.11.17"
chardet = "3.0.4"
idna = "3.7"
requests = "^2.22.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
