- name: Gather Policy Access Rule Details
  hosts: localhost
  connection: local
  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

- name: Verify Virtual Environment Activation
  command: source /app/venv/bin/activate && echo $VIRTUAL_ENV
  register: venv_activation
  changed_when: false

- name: Display Virtual Environment
  debug:
    msg: "Virtual Environment: {{ venv_activation.stdout }}"
