- name: Gather Policy Access Rule Details
  hosts: localhost
  connection: local

  vars:
    zpa_cloud:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret | default(omit) }}"
      customer_id: "{{ customer_id | default(omit) }}"
      cloud: "{{ cloud | default(omit) }}"

  tasks:
    - name: Check Python interpreter
      command: /app/venv/bin/python -c "import sys; print(sys.executable)"
      register: python_check

    - name: Check zscaler library
      command: /app/venv/bin/python -c "import zscaler; print(zscaler.__file__)"
      register: zscaler_check

    - name: Display Python and zscaler info
      ansible.builtin.debug:
        msg: |
          Python executable: {{ python_check.stdout }}
          zscaler library location: {{ zscaler_check.stdout }}

    - name: Get Details of All Policy Access Rules
      zscaler.zpacloud.zpa_policy_access_rule_info:
        provider: "{{ zpa_cloud }}"
      vars:
        ansible_python_interpreter: /app/venv/bin/python
