- name: App Connector Group
  hosts: localhost

  vars:
    zpa_cloud:
      client_id: "{{ lookup('env', 'ZPA_CLIENT_ID') }}"
      client_secret: "{{ lookup('env', 'ZPA_CLIENT_SECRET') }}"
      customer_id: "{{ lookup('env', 'ZPA_CUSTOMER_ID') }}"
      cloud: "{{ lookup('env', 'ZPA_CLOUD') | default(omit) }}"

  tasks:
    - name: Create a App Protection Security Profile
      zscaler.zpacloud.zpa_app_protection_security_profile:
        state: present
        name: "Example_App_Protection_Security_Profile"
        description: "Example_App_Protection_Security_Profile"
        paranoia_level: "1"
        incarnation_number: "6"
        predef_controls_version: "OWASP_CRS/3.3.0"
        # global_control_actions:
          # - "PREDEFINED:NONE"
          # - "CUSTOM:NONE"
          # - "WEBSOCKET:NONE"
          # - "THREATLABZ:NONE"
          # - "OVERRIDE_ACTION:NONE"
        -controls_info:
          - control_type: "PREDEFINED"
            count": "207"
          - control_type": "THREATLABZ"
            count": "23"
          - control_type: "WEBSOCKET_PREDEFINED"
            count": "11"
