- name: App Protection Custom Control
  hosts: localhost

  vars:
    zpa_cloud:
      client_id: "{{ lookup('env', 'ZPA_CLIENT_ID') }}"
      client_secret: "{{ lookup('env', 'ZPA_CLIENT_SECRET') }}"
      customer_id: "{{ lookup('env', 'ZPA_CUSTOMER_ID') }}"
      cloud: "{{ lookup('env', 'ZPA_CLOUD') | default(omit) }}"

  tasks:
    - name: Gather App Protection Predefined Control
      zscaler.zpacloud.zpa_app_protection_predefined_control_info:
        provider: "{{ zpa_cloud }}"
        name: "Failed to parse request body"
      register: result
    - name: predefined_controls
      debug:
        msg: "{{ result }}"


    # - name: Gather App Protection All Predefined Control
    #   zscaler.zpacloud.zpa_app_protection_all_predefined_controls_info:
    #     provider: "{{ zpa_cloud }}"
    #     # verion: OWASP_CRS/3.3.0
    #     # group_name: Preprocessors
    #   register: result
    # - name: predefined_controls
    #   debug:
    #     msg: "{{ result }}"


















    # - name: Create a App Protection Custom Controls (RESPONSE)
    #   zscaler.zpacloud.zpa_app_protection_custom_control:
    #     state: absent
    #     provider: "{{ zpa_cloud }}"
    #     name: "Example_App_Protection_Custom_Control"
        # description: "Example_App_Protection_Custom_Control"
        # action: "PASS"
        # default_action: PASS
        # paranoia_level: "2"
        # severity: "CRITICAL"
        # type: "REQUEST"
        # protocol_type: "HTTP"
        # rules:
        #   - conditions:
        #       - lhs: VALUE
        #         op: RX
        #         rhs: "test"
        #       - lhs: SIZE
        #         op: EQ
        #         rhs: "1000"
        #     names:
        #       - example1
        #       - example2
        #       - example3
        #     type: REQUEST_HEADERS

        #   - conditions:
        #       - lhs: VALUE
        #         op: RX
        #         rhs: "test"

        #       - lhs: SIZE
        #         op: LE
        #         rhs: "1000"
        #     names:
        #       - example1
        #       - example2
        #       - example3
        #     type: REQUEST_COOKIES

        #   - conditions:
        #       - lhs: SIZE
        #         op: EQ
        #         rhs: "1000"

        #       - lhs: VALUE
        #         op: CONTAINS
        #         rhs: "test-ansible"
        #     type: REQUEST_URI

        #   - conditions:
        #       - lhs: SIZE
        #         op: EQ
        #         rhs: "1000"

        #       - lhs: VALUE
        #         op: STARTS_WITH
        #         rhs: "test-ansible"
        #     type: QUERY_STRING

# Add validation:
# When action is REDIRECT, default_action_value must be set wiuth the redirect URL