- name: Policy rule
  hosts: localhost

  vars:
    zpa_cloud:
      client_id: "{{ lookup('env', 'ZPA_CLIENT_ID') }}"
      client_secret: "{{ lookup('env', 'ZPA_CLIENT_SECRET') }}"
      customer_id: "{{ lookup('env', 'ZPA_CUSTOMER_ID') }}"
      cloud: "{{ lookup('env', 'ZPA_CLOUD') | default(omit) }}"

  tasks:
    - name: Gather information about specific Posture Profile UDID
      zscaler.zpacloud.zpa_posture_profile_info:
        # name: "CrowdStrike_ZPA_Pre-ZTA"
      register: pp_crowdstrike_zta40
    - debug:
        msg: "{{ pp_crowdstrike_zta40}}"

    - name: pp_crowdstrike_zta40
      debug:
        msg: "{{ pp_crowdstrike_zta40}}"
