- name: App Connector Group
  hosts: localhost

  # vars:
  #   zpa_cloud:
  #     client_id: "{{ lookup('env', 'ZPA_CLIENT_ID') }}"
  #     client_secret: "{{ lookup('env', 'ZPA_CLIENT_SECRET') }}"
  #     customer_id: "{{ lookup('env', 'ZPA_CUSTOMER_ID') }}"
  #     cloud: "{{ lookup('env', 'ZPA_CLOUD') | default(omit) }}"

  tasks:
    - name: Ensure App Connector Group is absent (leftover)
      zscaler.zpacloud.zpa_app_connector_groups:
        state: absent
        name: "Example"
        description: "Example"
        country_code: CA
        dns_query_type: IPV4
        enabled: true
        latitude: "49.1041779"
        longitude: "-122.6603519"
        location: Langley City, BC, Canada
        upgrade_day: SUNDAY
        override_version_profile: true
        upgrade_time_in_secs: "66600"
        version_profile_id: "2"
