---
- name: Policy rule
  hosts: localhost

  tasks:
    - name: Gather ID for Posture Profiles CrowdStrike_ZPA_ZTA_40
      zscaler.zpacloud.zpa_posture_profile_info:
        name: CrowdStrike_ZPA_ZTA_40
      register: posture1

    - name: Display posture1 ID
      debug:
        msg: "{{ posture1.data[0].posture_udid }}"

    - name: Modify Ansible_Access_Policy_Rule
      zscaler.zpacloud.zpa_policy_access_rule:
        name: "Ansible_Access_Policy_Rule1"
        description: "Ansible_Access_Policy_Rule1"
        action: "ALLOW"
        operator: "AND"
        rule_order: "1"
        conditions:
          - operator: "OR"
            negated: false
            operands:
              - object_type: "POSTURE"
                lhs: "{{ posture1.data[0].posture_udid }}"
                rhs: "true"

