name: ZPA Test

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - master
  schedule:
    - cron: '0 15 * * 1-5' # UTC
  workflow_dispatch:

env:
  NAMESPACE: zscaler
  COLLECTION_NAME: zpacloud
  PYTHON_VERSION: 3.10

jobs:
  zpa-qa1-tenants:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        environment:
          - ZPA_QA_TENANT01
          - ZPA_QA_TENANT02
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 1.8.2

      - name: Get poetry cache directory
        id: poetry-cache
        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache poetry dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key:
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{
            hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install dependencies
        run: poetry install
        working-directory: ${{ github.workspace }}

      - name: Install Ansible
        run: pip install ansible

      - name: Build and install collection locally
        run: poetry run make install

      - name: Run tests with retry
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: poetry run ansible-playbook tests/integration/run_all_tests.yml
        env:
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          OKTA_CLIENT_ORGURL: ${{ secrets.OKTA_CLIENT_ORGURL }}
          OKTA_CLIENT_TOKEN: ${{ secrets.OKTA_CLIENT_TOKEN }}

  zpa-beta-tenants:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        environment:
          - ZPA_BETA_TENANT01
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 1.8.2

      - name: Get poetry cache directory
        id: poetry-cache
        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache poetry dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key:
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{
            hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install dependencies
        run: poetry install
        working-directory: ${{ github.workspace }}

      - name: Install Ansible
        run: pip install ansible

      - name: Build and install collection locally
        run: poetry run make install

      - name: Install dependencies
        run: poetry install

      - name: Run tests with retry
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: poetry run ansible-playbook tests/integration/run_all_tests.yml
        env:
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          OKTA_CLIENT_ORGURL: ${{ secrets.OKTA_CLIENT_ORGURL }}
          OKTA_CLIENT_TOKEN: ${{ secrets.OKTA_CLIENT_TOKEN }}
    needs:
      - zpa-qa1-tenants

  zpa-prod-tenants:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        environment:
          - ZPA_PROD_TENANT01
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 1.8.2

      - name: Get poetry cache directory
        id: poetry-cache
        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache poetry dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key:
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{
            hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install dependencies
        run: poetry install
        working-directory: ${{ github.workspace }}

      - name: Install Ansible
        run: pip install ansible

      - name: Build and install collection locally
        run: poetry run make install

      - name: Install dependencies
        run: poetry install

      - name: Run tests with retry
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: poetry run ansible-playbook tests/integration/run_all_tests.yml
        env:
          ZPA_CLIENT_ID: ${{ secrets.ZPA_CLIENT_ID }}
          ZPA_CLIENT_SECRET: ${{ secrets.ZPA_CLIENT_SECRET }}
          ZPA_CUSTOMER_ID: ${{ secrets.ZPA_CUSTOMER_ID }}
          ZPA_CLOUD: ${{ secrets.ZPA_CLOUD }}
          OKTA_CLIENT_ORGURL: ${{ secrets.OKTA_CLIENT_ORGURL }}
          OKTA_CLIENT_TOKEN: ${{ secrets.OKTA_CLIENT_TOKEN }}
    needs:
      - zpa-qa1-tenants
      - zpa-beta-tenants